namespace Clean.Architecture.Web.ApiModels;

// ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
public class ProductoDTO : CreateProductoDTO
{
  public ProductoDTO(int id, string nombre, string descripcion, string categoria, string? imagen) : base(nombre, descripcion,categoria,imagen)
  {
    Id = id;
  }
  public int Id { get; set; }
}

// Creation DTOs should not include an ID if the ID will be generated by the back end
public abstract class CreateProductoDTO
{
  protected CreateProductoDTO(string name, string descripcion, string categoria, string? imagen)
  {
    Nombre = name;
    Descripcion = descripcion;
    Categoria = categoria;
    Imagen = imagen;
  }
  public string Nombre { get; set; }
  public string Descripcion { get; set; }
  public string Categoria { get; set; }
  public string? Imagen { get; set; }
}
